/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;


/**
 *
 * @author arumia
 */
public class Input_Barang extends javax.swing.JFrame {

    public Connection con;
    public Statement stat;
    public String sql="";
    public ResultSet rs;
    
    /**
     * Creates new form Input_Barang
     */
    public Input_Barang() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        buttonExit = new javax.swing.JButton();
        buttonSave = new javax.swing.JButton();
        buttonRefresh = new javax.swing.JButton();
        jtextStokBarang = new javax.swing.JTextField();
        jtextKodeBarang = new javax.swing.JTextField();
        jtextNamaBarang = new javax.swing.JTextField();
        jtextHargaBarang = new javax.swing.JTextField();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB", 0, 16)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("FORM DATA BARANG");
        jPanel3.add(jLabel1);
        jLabel1.setBounds(0, 30, 340, 30);

        jLabel2.setText("Stok Barang");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(30, 200, 90, 30);

        jLabel3.setText("Kode Barang");
        jPanel3.add(jLabel3);
        jLabel3.setBounds(30, 80, 90, 30);

        jLabel4.setText("Nama Barang");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(30, 120, 90, 30);

        jLabel5.setText("Harga Barang");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(30, 160, 90, 30);

        buttonExit.setText("Exit");
        buttonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExitActionPerformed(evt);
            }
        });
        jPanel3.add(buttonExit);
        buttonExit.setBounds(220, 260, 70, 30);

        buttonSave.setText("Save");
        buttonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSaveActionPerformed(evt);
            }
        });
        jPanel3.add(buttonSave);
        buttonSave.setBounds(50, 260, 70, 30);

        buttonRefresh.setText("Refresh");
        buttonRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRefreshActionPerformed(evt);
            }
        });
        jPanel3.add(buttonRefresh);
        buttonRefresh.setBounds(130, 260, 80, 30);
        jPanel3.add(jtextStokBarang);
        jtextStokBarang.setBounds(130, 200, 170, 30);
        jPanel3.add(jtextKodeBarang);
        jtextKodeBarang.setBounds(130, 80, 170, 30);
        jPanel3.add(jtextNamaBarang);
        jtextNamaBarang.setBounds(130, 120, 170, 30);
        jPanel3.add(jtextHargaBarang);
        jtextHargaBarang.setBounds(130, 160, 170, 30);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 0, 350, 320);

        setBounds(0, 0, 358, 358);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExitActionPerformed
        dispose();
    }//GEN-LAST:event_buttonExitActionPerformed

    private void buttonRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRefreshActionPerformed
        jtextKodeBarang.setText(" ");
        jtextNamaBarang.setText(" ");
        jtextHargaBarang.setText(" ");
        jtextStokBarang.setText(" ");
    }//GEN-LAST:event_buttonRefreshActionPerformed

    private void buttonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSaveActionPerformed
        
        String kodebarang = jtextKodeBarang.getText();
        String namabarang = jtextNamaBarang.getText();
        String hargabarang = jtextHargaBarang.getText();
        String stokbarang = jtextStokBarang.getText();
        
        try
        {
            String dbname="jdbc:ucanaccess://E:/TA PBO/AplikasiSederhana(DB_MsAccess)/db_barang.accdb";
            Connection con = DriverManager.getConnection(dbname);
            Statement statement = con.createStatement();
            String sql="insert into tb_databarang values('"+kodebarang+"','" +
                    namabarang+"','"+
                    hargabarang+"','"+
                    stokbarang+"')";
            
            statement.executeUpdate(sql);
            statement.close();
            
            JOptionPane.showMessageDialog(null,"Data berhasil ditambahkan","Insert Data",JOptionPane.INFORMATION_MESSAGE);
            con.close();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"error: "+e,"Data gagal ditambahkan",JOptionPane.WARNING_MESSAGE);
        }    
    }//GEN-LAST:event_buttonSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Input_Barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Input_Barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Input_Barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Input_Barang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Input_Barang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonExit;
    private javax.swing.JButton buttonRefresh;
    private javax.swing.JButton buttonSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jtextHargaBarang;
    private javax.swing.JTextField jtextKodeBarang;
    private javax.swing.JTextField jtextNamaBarang;
    private javax.swing.JTextField jtextStokBarang;
    // End of variables declaration//GEN-END:variables
}
